services:
  bootstrap:
    build: api/
    container_name: kafka_bootstrap
    command: sh bootstrap/start_bootstrap.sh
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    env_file:
      - .env
    volumes:
      - .:/app
    restart: "no"
    networks:
      - default

  web:
    build: api/
    container_name: fastapi_app
    ports:
      - "${FASTAPI_PORT}:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app/api
    command: uvicorn main:app --host ${FASTAPI_HOST} --port 8000 --reload --reload-dir /app/api --reload-dir /app/api/routes
    depends_on:
      bootstrap:
        condition: service_completed_successfully

  crypto-producer:
    build: api/
    container_name: kafka_producer
    command: python start_producer.py
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    env_file:
      - .env
    depends_on:
      bootstrap:
        condition: service_completed_successfully

  crypto-consumer:
    build: api/
    container_name: kafka_consumer
    command: python start_consumer.py
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    env_file:
      - .env
    depends_on:
      bootstrap:
        condition: service_completed_successfully

networks:
  default:
    external: true
    name: crypto-prediction-network
